name: jupyterlab-plugin-playground-lite

channels:
- conda-forge

dependencies:
- build
- python=3.10
- mamba
- pydata-sphinx-theme
- myst-parser
- ipywidgets>=8.0,<9
- jupyterlab>=3.5.0,<4
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlite>=0.1.2,<0.2.0
- jupyterlite-sphinx>=0.9.1,<0.10.0
- nodejs=18
