name: jupyterlab-plugin-playground-lite

channels:
- conda-forge

dependencies:
- python=3.10
- pip
- pydata-sphinx-theme
- myst-parser
- ipywidgets>=8.0,<9
- jupyterlab>=4.0.0,<5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlite-core>=0.7.0,<0.8
- jupyterlite-sphinx>=0.22.0,<0.23
- jupyterlite-javascript-kernel>=0.3.0,<0.4
- nodejs=18
- pip:
  - build
