# a mybinder.org-ready environment for demoing jupyterlab-plugin-playground
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-plugin-playground-demo
#
name: jupyterlab-plugin-playground-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3.6.0a5,<4.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
  - jupyterlab-lsp
