# a mybinder.org-ready environment for demoing jupyterlab-plugin-playground
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-plugin-playground-demo
#
name: jupyterlab-plugin-playground-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.13.0a0
  - jupyterlab >=4,<5.0.0a0
  # labextension build dependencies
  - nodejs >=18,<21
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
  - jupyterlab-lsp
  - pip:
      # JupyterLab 4-compatible JS logs extension
      - git+https://github.com/jupyterlab-contrib/jupyterlab-js-logs.git@a2c64b476cbd83cda86e1d2c1f627fc627a99698
